name: Publish Articles

on:
  push:
    branches: [ "main" ]
    paths:
      - published/**/*.md
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Delete Existing Publish Branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: published
    - name: Publish Articles
      uses: LarchLiu/actions-save-files@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: published
        publish_dir: published
        destination_dir: .
        exclude_assets: '.github,README.md'
